services:
 mysql-container:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: admin
  ports:
   - "3306:3306"
  volumes:
   - ./mysql-init:/docker-entrypoint-initdb.d
  networks:
   - basboosify-network
  hostname: mysql-host-productsmicroservice

 products-microservice:
  image: mxku/basboosify-products-microservice:v1.0
  environment:
   MYSQL_HOST: mysql-host-productsmicroservice
   MYSQL_PASSWORD: admin
  ports:
   - "8080:8080"
  networks:
   - basboosify-network

 postgres-container:
  image: postgres:latest
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: BasboosifyUsers
  ports:
   - "5432:5432" 
  volumes:
   - ./postgres-init:/docker-entrypoint-initdb.d
  networks:
   - basboosify-network

 users-microservice:
  image: mxku/basboosify-users-microservice:v1.0
  environment:
   POSTGRES_HOST: postgres-container
   POSTGRES_PASSWORD: admin
  ports:
   - "9090:9090"
  networks:
   - basboosify-network

networks:
 basboosify-network:
  driver: bridge